name: silatar_v2
description: "SILATAR V2 - Aplikasi Mobile Layanan Kementerian Agama Tanah Datar"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.2

  # HTTP & API
  dio: ^5.4.0
  http: ^1.2.2

  # Local Storage
  shared_preferences: ^2.3.3

  # Date formatting
  intl: ^0.19.0

  # PDF Generation & Sharing
  pdf: ^3.10.7
  printing: ^5.12.0
  path_provider: ^2.1.1

  # Image caching
  cached_network_image: ^3.4.1

  # Location & Maps
  geolocator: ^13.0.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # Image Picker
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/template/
    - assets/images/ikon/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
